name: dev-build-deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: chrislennon/action-aws-cli@v1.1
      - name: install dependencies
        run: yarn --production=false
      - name: lint
        run: yarn lint
      - name: tsc
        run: yarn tsc
      - name: deploy the build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: serverless deploy --force
